nodeLinker: node-modules
packageExtensions:
  "@docusaurus/mdx-loader@*":
    peerDependencies:
      "@babel/core": "*"
  "@docusaurus/plugin-content-blog@*":
    peerDependencies:
      "@babel/core": "*"
  "@docusaurus/plugin-content-docs@*":
    peerDependencies:
      "@babel/core": "*"
  "@docusaurus/plugin-content-pages@*":
    peerDependencies:
      "@babel/core": "*"
  "@docusaurus/plugin-debug@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@docusaurus/plugin-google-analytics@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@docusaurus/plugin-google-gtag@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@docusaurus/plugin-sitemap@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@docusaurus/preset-classic@*":
    peerDependencies:
      "@babel/core": "*"
      prism-react-renderer: "*"
      webpack: "*"
  "@docusaurus/theme-classic@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@docusaurus/theme-common@*":
    peerDependencies:
      "@babel/core": "*"
  "@docusaurus/theme-search-algolia@*":
    peerDependencies:
      "@babel/core": "*"
      prism-react-renderer: "*"
      webpack: "*"
  "@docusaurus/utils-validation@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
